export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const REGISTER_USER = "REGISTER_USER";
export const IMAGES_GET_SUCCESS = "IMAGES_GET_SUCCESS";
export const IMAGES_GET_FAILURE = "IMAGES_GET_FAILURE";
export const GET_AUTH_INFO_SUCCESS = "GET_AUTH_INFO_SUCCESS";
export const GET_AUTH_INFO_FAILURE = "GET_AUTH_INFO_FAILURE";
